### ISSUE TITLE
Bind9 missing new 'allow-query-on' keyword parser

### ISSUE THREAD

**Issue by egberts** [Eugeny/reconfigure#21]
Bind 9.11 introduced a new keyword `allow-query-on` that looks like:

```
allow-query-on { 
 external_bastion_ip_acl; // that public DNS server
 external_downstream_nameservers_acl;
 };
```

It resulted in a parse error of:

```
Traceback (most recent call last):
  File "./bind.py", line 24, in <module>
    nodes = includer.compose(NAMED_CONF, node_tree)
  File "/home/steve/.local/lib/python3.5/site-packages/reconfigure/includers/auto.py", line 13, in compose
    self.compose_rec(origin, origin, tree)
  File "/home/steve/.local/lib/python3.5/site-packages/reconfigure/includers/auto.py", line 36, in compose_rec
    subtree = self.parser.parse(content)
  File "/home/steve/.local/lib/python3.5/site-packages/reconfigure/parsers/nginx.py", line 26, in parse
    raise Exception('Invalid tokens: %s. Tokens: %s' % (remainder, tokens))
Exception: Invalid tokens: allow-query-on { 
 external_bastion_ip_acl; // that public DNS server
 external_downstream_nameservers_acl;
 };
```

Let me know what I can do.

**Comment by egberts** [comment]
Same thing with `allow-transfer` keyword.
